import os, stat

env = Environment()

def write_to_file(fn, cont, executable = None):
    """Write some contect to file"""
    f = open(fn, 'w')
    f.write(cont)
    f.close()
    
    if executable is True:
        os.chmod(
            fn, 
            os.stat(fn).st_mode | stat.S_IEXEC
        )

# TODO: extend to a class
def iverilog_compile(target, source, env):
    filelist_fn = 'filelist.iverilog'
    filelist_str = "\n".join(list(map(str, source))) + "\n"

    write_to_file(filelist_fn, filelist_str)
    
    top_opt = "-o %s" % str(target[0])
    tgt_opt = "-s %s" % str(target[0])
    inc_opt = "-I " + env["inc_dir"]
    iv_cmd = \
        " ".join([
            "iverilog -f %s" % filelist_fn,
            inc_opt,
            tgt_opt,
            top_opt,
        ]) + "\n" + \
        "./%s" % str(target[0])
    
    script_fn = 'sim_%s.sh' % str(target[0])

    write_to_file(script_fn, iv_cmd, executable = True)

    return None

bld = Builder(action = iverilog_compile)
env = Environment(BUILDERS = {'IVERILOG' : bld})

env['inc_dir'] = '../include'

vfiles = Glob('../rtl/verilog/*.v') + Glob('../bench/tb_*.v')

tb_dff = env.IVERILOG('tb_dff', vfiles)
tb_counter = env.IVERILOG('tb_counter', vfiles)
tb_full_adder = env.IVERILOG('tb_full_adder', vfiles)

Clean(tb_dff, 'sim_tb_dff.sh')
Clean(tb_counter, 'sim_tb_counter.sh')
Clean(tb_full_adder, 'sim_tb_full_adder.sh')
Clean(tb_dff, "filelist.iverilog")
Clean(tb_counter, "filelist.iverilog")
Clean(tb_full_adder, "filelist.iverilog")

